### ISSUE TITLE
imgcat support? 

### ISSUE THREAD

**Issue by linux-china** [cbeust/kash#11]
Display image on console.  you can display image on console from your data, such as report diagram, QR code,  PlantUML diagram etc. 

```
fun imcat(url: String)

fun imcat(file: File)

fun imcat( buffer: BufferedImage)

fun imcat(bytes: ByteArray) 
```

**Comment by cbeust** [comment]
This would require support from the underlying console, so I'm not sure it's feasible by Kash alone.

Please reopen if I'm misunderstanding what you're asking.
