### ISSUE TITLE
GraalVM introduce to support JS, Ruby Python and LLVM?

### ISSUE THREAD

**Issue by linux-china** [cbeust/kash#12]
Of course, I love kotlin :)  
But sometimes I write some scripts with other languages.  with js, lli, python and ruby as runtime functions, and It will be fast to execute the scripts without new process created.  It's also good for Maven build run fast.

**Comment by cbeust** [comment]
I'm not sure I see the connection between GraalVM and supporting additional languages.

Supporting more languages could be done pretty easily (just need to look up additional engines with the JvmScript223 factory), but determining what language is a specific line would be a bit inefficient (but doable: keep parsing until an engine accepts the code).

Kotlin is my focus for now, though.
